on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
      - '.github/workflows/check-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/check-backend.yml'

# Only run against current ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: check
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache-dependency-path: pyproject.toml
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ./backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-lint
      - name: Install dependencies
        run: poetry install --with dev
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Lint
        run: poetry run task lint

  test:
    runs-on: ubuntu-latest
    name: test
    container: python:3.10
    defaults:
      run:
        working-directory: ./backend

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ./backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-test
      - name: Install dependencies
        run: poetry install --with test
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Setup Database
        run: |
          psql -f data/client.sql
          psql -c "SELECT * FROM client"
        env:
          PGHOST: postgres
          PGDATABASE: postgres
          PGUSER: postgres
          PGPASSWORD: postgres
          PAGER:
      - name: Test
        run: poetry run task test
        env:
          POSTGRES_SERVER: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_TEST_DB: postgres

          POSTGRES_CLIENT_SERVER: postgres
          POSTGRES_CLIENT_USER: postgres
          POSTGRES_CLIENT_PASSWORD: postgres
          POSTGRES_TEST_CLIENT_DB: postgres

          # Dummy key pair for testing only
          PUBLIC_KEY: |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJ8wr6sUXlocWYzy3iidqGDYqYCXI
            tzzPEZopV+pVf4EVMJJsRgCjywQf75b9DbS/xm5f0z2COa9hQ8WgY6IxaQ==
            -----END PUBLIC KEY-----
          PRIVATE_KEY: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIPKmf6c6dCaqHyw0vxOxzStZ3HSFjLLFEkaigA2H/LzzoAoGCCqGSM49
            AwEHoUQDQgAEJ8wr6sUXlocWYzy3iidqGDYqYCXItzzPEZopV+pVf4EVMJJsRgCj
            ywQf75b9DbS/xm5f0z2COa9hQ8WgY6IxaQ==
            -----END EC PRIVATE KEY-----

