name: Check Frontend
on: [push]

# Only run against current ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install --ignore-scripts

      - name: Run Lint
        working-directory: ./frontend
        run: npm run lint

      - name: Check TypeScript
        working-directory: ./frontend
        run: npm run typecheck
