on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
      - '.github/workflows/check-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/check-backend.yml'

# Only run against current ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: check
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache-dependency-path: pyproject.toml
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-lint
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.4.2"
      - name: Install dev deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --only dev
      - name: Lint
        run: poetry run task lint
